apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order-namespace
spec:
  type: LoadBalancer
  selector:
    app: order
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
